### PR TITLE
Added support for off('*', '*') and off('*', someHandler).

### PR DESCRIPTION
**Pull request by roblinton**
Regarding issue:
https://github.com/RIAEvangelist/event-pubsub/issues/3

### CODE REVIEW

**Comment by roblinton** [comment]
This code doesn't work.  Sorry about that!

**Comment by RIAEvangelist** [comment]
NP :) thanks for the shot!

**Comment by roblinton** [comment]
I've since fixed the problem but I'll hold off on resubmitting until we know whether we want to keep this functionality in the library.  FWIW, I discovered the problem while using the node-ipc library.  It's not a happy camper with the latest release.  :)

One last thing, this pull request also changed a behaviour.  If the same handler is bound twice to the same event, currently removing it will only remove one of the handlers if they are stored adjacently in the _events_[event] array, or both if they are not adjacent.  This pull removes all the matching handlers regardless of their position in the array.

**Comment by RIAEvangelist** [comment]
hmm interesting. perhaps we should not allow the same handler to be bound to the same event multiple times.

The appropriate way to do this would be `.bind`ing a different scope to the function thus getting a new and separate reference to it.

It does not seem logical to allow multiple binds of the exact same thing, but then again it doesnt seem effecient to iterate on every bind to check either.

**Comment by roblinton** [comment]
Yeah, I agree... instances where you actually want the same handler bound
to the same event are unusual and in most cases would probably indicate a
bug.  However, personally I'm irritated by libraries that think they know
better than me.

EventEmitter's behaviour is to happily oblige duplicates, but removes only
the first instance when removeListener is called.

Perhaps it's worth mocking that for the sake of consistency?

2016-09-28 16:53 GMT-04:00 Brandon Nozaki Miller <notifications@github.com>:

**Comment by RIAEvangelist** [comment]
agreed.

**Comment by RIAEvangelist** [comment]
I think the reason I removed this functionality was to do with people referencing undefined.

IE they would do 
` .on('event',awesomeHandler.bind('poop')) `
and then 
` .off('event',awesomeHandler) ` out of scope or something. 

looking into it now.

**Pull request closed without merging**
